# Generated by Django 3.2.19 on 2023-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=25)),
                ('email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('comment', models.TextField(editable=False)),
            ],
        ),
    ]
