# Generated by Django 3.2.19 on 2023-07-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdata',
            old_name='email',
            new_name='email_comment',
        ),
        migrations.RenameField(
            model_name='commentdata',
            old_name='name',
            new_name='name_comment',
        ),
    ]
