# Generated by Django 3.2.19 on 2023-07-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230726_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentData',
        ),
    ]
